### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by MBoui** [subzerocloud/blue-steel#2]
Hi teams,

I followed the instructions to get the source code for this project.
So I wonder what will be the next step to get the source code.
We are considering using a solution of this type for our infrastructure, only for security reasons we must have a reading of the software.

Thanks for your help.

**Comment by ruslantalpa** [comment]
@MBoui I am sorry abut the confusion/situation i created by forgetting to remove the readme part about the license (i've removed the text now). That offer was once valid (for a kind of "alpha" stage to get some eyes on the code for the feedback) but now I've progressed on the codebase and i am close to releasing it for production in 1-2 months (but that offer is not current now).

Today i am at the stage of having the code work with postgresql/sqlite/clickhouse packaged as a single executable (or in docker) but also as node package/lib that opens up the possibility  of running it in any env that runs JS (cloudflare workers/deno/Lambda) which i am kind of exited about :).

Again, sorry for the situation
